






//------------------
//For API

//Template for async actions (REgex)
//export const $NAME$_INIT_API = '$NAME$_INIT_API'
//export const $NAME$_SUCCESS_API = '$NAME$_SUCCESS_API'
//export const $NAME$_FAILURE_API = '$NAME$_FAILURE_API'

// cart actions
export const LOAD_CART_INIT_API = 'LOAD_CART_INIT_API'
export const LOAD_CART_SUCCESS_API = 'LOAD_CART_SUCCESS_API'
export const LOAD_CART_FAILURE_API = 'LOAD_CART_FAILURE_API'

export const ADD_CART_ITEM_INIT_API = 'ADD_CART_ITEM_INIT_API'
export const ADD_CART_ITEM_SUCCESS_API = 'ADD_CART_ITEM_SUCCESS_API'
export const ADD_CART_ITEM_FAILURE_API = 'ADD_CART_ITEM_FAILURE_API'

export const SUB_CART_ITEM_INIT_API = 'SUB_CART_ITEM_INIT_API'
export const SUB_CART_ITEM_SUCCESS_API = 'SUB_CART_ITEM_SUCCESS_API'
export const SUB_CART_ITEM_FAILURE_API = 'SUB_CART_ITEM_FAILURE_API'

export const ADD_CART_ITEM_UNSAFE = 'ADD_CART_ITEM_UNSAFE'
export const SUB_CART_ITEM_UNSAFE = 'SUB_CART_ITEM_UNSAFE'

// product actions
export const FETCH_PRODUCTS_INIT_API = 'FETCH_PRODUCTS_INIT_API'
export const FETCH_PRODUCTS_SUCCESS_API = 'FETCH_PRODUCTS_SUCCESS_API'
export const FETCH_PRODUCTS_FAILURE_API = 'FETCH_PRODUCTS_FAILURE_API'

// user actions
export const POST_LOGIN_INIT_API = 'POST_LOGIN_INIT_API'
export const POST_LOGIN_SUCCESS_API = 'POST_LOGIN_SUCCESS_API'
export const POST_LOGIN_FAILURE_API = 'POST_LOGIN_FAILURE_API'

export const POST_SIGNUP_INIT_API = 'POST_SIGNUP_INIT_API'
export const POST_SIGNUP_SUCCESS_API = 'POST_SIGNUP_SUCCESS_API'
export const POST_SIGNUP_FAILURE_API = 'POST_SIGNUP_FAILURE_API'
